# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b963a3febf832e3f9849ea60a69ed0cbf32d49e02e89c0dc205b034d1407ee674e40097076c5d2e0edecec6a7423461c6ade73faf6b511f68d8403d6950f5f26

test:
  secret_key_base: 564c95379b6e0f1bd30dd1f979c40fe64d937c13d3bd5828d1b20a93233b6fd0414ee1487716bc8c8c2fa6b96ca75307087891bca8dd260eaba4d79083517922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
